"""Provenance records.

Every dataset and parameter set in AquaOS carries a :class:`Provenance`. Synthetic data is allowed, but it must say
so: ``synthetic=True`` and a description of how it was generated. Report builders call :func:`require_provenance`
and refuse to render anything without it.
"""

from __future__ import annotations

import datetime as dt
import hashlib
from pathlib import Path
from typing import Any, Literal, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field, model_validator

SYNTHETIC_LABEL = "SYNTHETIC"

Kind = Literal["primary", "derived", "synthetic", "assumption"]


class Provenance(BaseModel):
    """Where a dataset or parameter came from.

    ``kind`` distinguishes:

    * ``primary``: taken directly from a primary source document or API.
    * ``derived``: computed from primary sources. ``derivation`` says how.
    * ``synthetic``: generated by AquaOS. Never presented as real.
    * ``assumption``: a modeling choice with no source. It must be stated and is open to sensitivity analysis.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    title: str
    kind: Kind
    source_url: str | None = None
    source_document: str | None = None
    retrieved: dt.date | None = None
    license: str | None = None
    units: dict[str, str] = Field(default_factory=dict)
    derivation: str | None = None
    notes: str | None = None
    sha256: str | None = None
    parents: tuple[Provenance, ...] = ()

    @property
    def synthetic(self) -> bool:
        """True when any part of this data is synthetic or an unsourced assumption."""
        return self.kind in ("synthetic", "assumption") or any(p.synthetic for p in self.parents)

    @property
    def label(self) -> str:
        return SYNTHETIC_LABEL if self.synthetic else self.kind.upper()

    @model_validator(mode="after")
    def _check_required_fields(self) -> Provenance:
        if self.kind == "primary" and not (self.source_url and self.retrieved):
            raise ValueError(f"primary provenance '{self.title}' needs source_url and retrieved date")
        if self.kind == "derived" and not (self.derivation and (self.parents or self.source_url)):
            raise ValueError(f"derived provenance '{self.title}' needs a derivation and a parent or source_url")
        if self.kind in ("synthetic", "assumption") and not (self.derivation or self.notes):
            raise ValueError(f"{self.kind} provenance '{self.title}' must explain how it was produced")
        return self

    def summary(self) -> str:
        parts = [f"[{self.label}] {self.title}"]
        if self.source_url:
            parts.append(f"source: {self.source_url}")
        if self.source_document:
            parts.append(f"doc: {self.source_document}")
        if self.retrieved:
            parts.append(f"retrieved {self.retrieved.isoformat()}")
        if self.derivation:
            parts.append(f"derivation: {self.derivation}")
        return "; ".join(parts)

    def flatten(self) -> list[Provenance]:
        """This record and every ancestor, depth first, without duplicates."""
        seen: dict[str, Provenance] = {}
        stack: list[Provenance] = [self]
        while stack:
            p = stack.pop()
            key = p.model_dump_json()
            if key not in seen:
                seen[key] = p
                stack.extend(p.parents)
        return list(seen.values())


def synthetic(title: str, how: str, units: dict[str, str] | None = None, **kw: Any) -> Provenance:
    """Shorthand for a synthetic provenance record."""
    return Provenance(title=title, kind="synthetic", derivation=how, units=units or {}, **kw)


def assumption(title: str, why: str, units: dict[str, str] | None = None, **kw: Any) -> Provenance:
    """Shorthand for a stated modeling assumption."""
    return Provenance(title=title, kind="assumption", notes=why, units=units or {}, **kw)


@runtime_checkable
class HasProvenance(Protocol):
    @property
    def provenance(self) -> Provenance: ...


def require_provenance(obj: object, what: str = "object") -> Provenance:
    """Return ``obj.provenance`` or raise. Report and plot builders use this as a gate."""
    prov = getattr(obj, "provenance", None)
    if not isinstance(prov, Provenance):
        raise ValueError(f"{what} has no provenance record; refusing to render it")
    return prov


def file_sha256(path: str | Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()
